# https://docs.drone.io/pipeline/docker/examples/languages/golang/
kind: pipeline
type: docker
name: default

steps:
- name: go-init
  image: golang:1.17.13-buster
  pull: if-not-exists # always if-not-exists never
  volumes:
    - name: go_cache
      path: /go
  environment:
    GOPATH: /go
    GOPROXY: https://goproxy.cn,direct
    GOPRIVATE: "*.gitlab.com,*.gitee.com,*.sinlov.cn"
    GO111MODULE: on
    CGO_ENABLED: 0
    GOOS: linux
    GOARCH: amd64
  commands:
    - pwd
    - make env
    - make init dep
  when:
    event:
      - push
- name: go-test
  image: golang:1.17.13-buster
  pull: if-not-exists # always if-not-exists never
  volumes:
    - name: go_cache
      path: /go
  environment:
    GOPATH: /go
    GOPROXY: https://goproxy.cn,direct
    GOPRIVATE: "*.gitlab.com,*.gitee.com,*.sinlov.cn"
    GO111MODULE: on
    CGO_ENABLED: 0
    GOOS: linux
    GOARCH: amd64
  commands:
    - make test
  when:
    event:
      - push
- name: go-dist-test
  image: golang:1.17.13-buster
  pull: if-not-exists # always if-not-exists never
  volumes:
    - name: go_cache
      path: /go
    - name: go_dist_test
      path: /go_dist_test
  environment:
    GOPATH: /go
    GOPROXY: https://goproxy.cn,direct
    GOPRIVATE: "*.gitlab.com,*.gitee.com,*.sinlov.cn"
    GO111MODULE: on
    CGO_ENABLED: 0
    GOOS: linux
    GOARCH: amd64
  commands:
    - make cleanAllDist distTestTar
    - cp ./dist/**/**.gz /go_dist_test/
  when:
    event:
      - push
- name: go-dist-release
  image: golang:1.17.13-buster
  pull: if-not-exists # always if-not-exists never
  volumes:
    - name: go_cache
      path: /go
    - name: go_dist_release
      path: /go_dist_release
  environment:
    GOPATH: /go
    GOPROXY: https://goproxy.cn,direct
    GOPRIVATE: "*.gitlab.com,*.gitee.com,*.sinlov.cn"
    GO111MODULE: on
    CGO_ENABLED: 0
    GOOS: linux
    GOARCH: amd64
  commands:
    - make cleanAllDist distReleaseTar
    - cp ./dist/**/**.gz /go_dist_release/
  when:
    event:
      - tag

volumes: # need admin open Trusted
  - name: go_cache
    host:
      path: /tmp/cache/go
  - name: go_dist_test
    host:
      path: /tmp/cache/dist/test/go
  - name: go_dist_release
    host:
      path: /tmp/cache/dist/release/go