# copy right
# Licenses http://www.apache.org/licenses/LICENSE-2.0
# more info see https://docs.docker.com/compose/compose-file/ or https://docker.github.io/compose/compose-file/
version: '3.7'

networks:
  default:
#volumes:
#  web-data:
services:
  fastEncryptDecode:
    container_name: '${ROOT_DOCKER_CONTAINER}'
    image: '${ROOT_DOCKER_IMAGE_NAME}:${ROOT_DOCKER_IMAGE_TAG}' # see local docker file
#    ports:
#      - "38080:38080"
    volumes:
      - "$PWD:/usr/src/myapp"
    environment:
      - ENV_WEB_HTTPS_ENABLE=false
      - ENV_WEB_AUTO_HOST=false
#      - ENV_WEB_HOST=${ENV_WEB_HOST}:38080
      #      - ENV_WEB_HOST=0.0.0.0:38080
    working_dir: "/usr/src/myapp"
    command: ["make", "dep", "test"]