name: 🐞Bug report
title: "[Bug]: "
description: Create a report to help us improve
#assignees:
#  - octocat
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected by the issue?
      multiple: true
      options:
        - cli
        - server
        - web-ui
        - CI/CD
        - other
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `system version`
      render: shell
      placeholder: |
        get system info by command
        # UNIX like
        $ uname -a
        # linux
        $ lsb_release -a
        # macOS
        $ sw_vers
        # windows
        $ systeminfo

        # OS: [e.g. iOS]
        # Browser [e.g. chrome, safari]
        # Version [e.g. 22]
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Logs? Screenshots? Anything that will give us more context about the issue you are encountering!
        Sometimes a picture is worth a thousand words, but please try not to insert an image of logs / text
        and copy paste the text instead.

        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Read the [Contributing Guidelines](../blob/main/.github/CONTRIBUTING_DOC/CONTRIBUTING.md).
          required: true
        - label: Check that there isn't [already an issue](../issues) that reports the same bug to avoid creating a duplicate.
          required: true
        - label: Checked that the bug isn't fixed in the `next` version already.
          required: true
