## more doc see
# https://docs.github.com/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#approve-a-pull-request

name: auto merge dependabot
on: pull_request

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Enable auto-merge for Dependabot PRs
        # Automatically merge the following dependency upgrades:
        if: "${{  steps.metadata.outputs.dependency-names == '@actions/core' ||
                  steps.metadata.outputs.dependency-names == 'actions/checkout' ||
                  steps.metadata.outputs.dependency-names == 'actions/setup-go' ||
                  steps.metadata.outputs.dependency-names == 'github.com/stretchr/testify' ||
                  steps.metadata.outputs.dependency-names == 'github.com/sinlov-go/unittest-kit' ||
                  steps.metadata.outputs.dependency-names == 'codecov/codecov-action' ||
                  steps.metadata.outputs.dependency-names == 'convention-change/conventional-version-check'
            }}"

        run: |
          gh pr edit "$PR_URL" --add-label "dependencies"
          gh pr merge --auto --merge '${{ github.event.pull_request.html_url }}'
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}