name: ci

on:
  push:
    paths-ignore:
      - '**/README.md'
    branches:
      - 'main'
      - 'release-*'
      - 'FE-*'
      - '*-feature-*'
      - 'BF-*'
      - '*-bug-*'
      - 'PU-*'
      - 'DOC-*'
      - '*-documentation-*'
      - '*-hotfix-*'
    tags:
      - '*' # Push events to matching *, i.e. 1.0.0 v1.0, v20.15.10
  pull_request:
    paths-ignore:
      - '**/README.md'
    types: # https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#pull_request
      - opened
      - reopened
      - closed
    branches:
      - 'main'
      - 'release-*'
      - 'DOC-*'
      - 'hotfix-*'

permissions:
  contents: write
  discussions: write

jobs:
  version:
    name: version
    uses: ./.github/workflows/version.yml

  golang-ci:
    name: golang-ci
    needs:
      - version
    uses: ./.github/workflows/golang-ci.yml
    secrets: inherit

  go-build-check-main:
    name: go-build-check-main
    needs:
      - version
      - golang-ci
    if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/main' ) || github.base_ref == 'main' }}
    uses: ./.github/workflows/go-release-platform.yml
    secrets: inherit
    with:
      version_name: latest

  go-release-platform:
    name: go-release-platform
    needs:
      - version
      - golang-ci
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/go-release-platform.yml
    secrets: inherit
    with:
      version_name: ${{ needs.version.outputs.tag_name }}
      upload_artifact_name: go-release

  deploy-tag:
    needs:
      - version
      - go-release-platform
    name: deploy-tag
    uses: ./.github/workflows/deploy-tag.yml
    if: startsWith(github.ref, 'refs/tags/')
    secrets: inherit
    with:
      prerelease: true
      tag_name: ${{ needs.version.outputs.tag_name }}
      tag_changes: ${{ needs.version.outputs.cc_changes }}
      download_artifact_name: go-release