name: ci

on:
  push:
    paths-ignore:
      - '**/README.md'
      - '**/doc-dev/*'
    branches:
      # - 'main'
      - 'release-*'
      - '*-feature-*'
      - '*-enhancement-*'
      - '*-hotfix-*'
      - '*-bug-*'
      - '*-documentation-*'
      - 'BF-*'
      - 'FE-*'
      - 'PU-*'
      - 'DOC-*'
    tags:
      - '*' # Push events to matching *, i.e. 1.0.0 v1.0, v20.15.10
  pull_request:
    paths-ignore:
      - '**/README.md'
    types: # https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#pull_request
      - opened
      - reopened
      - closed
    # branches:
    #   - 'main'
    #   - 'release-*'
    #   - 'DOC-*'
    #   - 'hotfix-*'

permissions: # https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#permissions
  contents: write
  discussions: write

jobs:
  version:
    name: version
    uses: ./.github/workflows/version.yml

  golang-ci:
    name: golang-ci
    needs:
      - version
    uses: ./.github/workflows/golang-ci.yml
    secrets: inherit
    with:
      run_test_case: true
      run_golangci_lint: true
      run_benchmark: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/main' ) || github.base_ref == 'main' }}
      run_test_coverage: true

  go-build-check-main:
    name: go-build-check-main
    needs:
      - version
      - golang-ci
    if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/main' ) || github.base_ref == 'main' }}
    uses: ./.github/workflows/go-release-platform.yml
    secrets: inherit
    with:
      version_name: latest
      go_build_id: ${{ needs.version.outputs.short_sha }}

  go-release-platform:
    name: go-release-platform
    needs:
      - version
      - golang-ci
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/go-release-platform.yml
    secrets: inherit
    with:
      version_name: ${{ needs.version.outputs.tag_name }}
      go_build_id: ${{ needs.version.outputs.short_sha }}
      # upload_artifact_name: go-release

  deploy-tag:
    needs:
      - version
      - go-release-platform
    name: deploy-tag
    uses: ./.github/workflows/deploy-tag.yml
    if: startsWith(github.ref, 'refs/tags/')
    secrets: inherit
    with:
      dry_run: false # open/close dry run
      prerelease: true
      tag_name: ${{ needs.version.outputs.tag_name }}
      tag_changes: ${{ needs.version.outputs.cc_changes }}
      # download_artifact_name: go-release # download artifact name, download from actions/upload-artifact, as: {download_artifact_name}-{tag_name}-*, empty is not download